### ISSUE TITLE
Images and Colours

### ISSUE THREAD

**Issue by willcrutchley** [lohriialo/illustrator-scripting-python#2]
How would I go about adding images using this? 
Also, when I attempt to add a fillColor (on a rectangle like you made in the hello world tutorial) I get the error: `TypeError: Cannot put <win32com.gen_py.None.CMYKColor> in VARIANT` would you be able to provide examples for these things?
Cheers

**Comment by lohriialo** [comment]
Are you looking for something like this?

```
docRef = app.Documents.Add()
rectRef = docRef.PathItems.Rectangle(700, 50, 100, 100)
color = Dispatch("Illustrator.CMYKColor")
color.Cyan = 10
color.Magenta = 35
color.Yellow = 50
color.Black = 5
rectRef.FillColor = color
```
